name: Rust

on:
  push:
    branches: ['*']
    tags:
      - 'release/*'
  pull_request:
    branches: ['*']

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set_tag.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Tag
        id: set_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "Using existing tag ${GITHUB_REF#refs/tags/}"
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            TAG_NAME="build-${{ github.sha }}"
            echo "Creating new tag $TAG_NAME"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          fi

  linux-x86_64:
    name: Linux x86_64
    runs-on: ubuntu-20.04
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - run: cargo build --all-features --release && mkdir -p rstun-linux-x86_64
          && mv target/release/rstunc ./rstun-linux-x86_64/
          && mv target/release/rstund ./rstun-linux-x86_64/
          && tar zcf rstun-linux-x86_64.tar.gz ./rstun-linux-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          name: Build ${{ github.sha }}
          files: |
            rstun-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-musl-x86_64:
    name: Linux musl x86_64
    runs-on: ubuntu-20.04
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - run:
          sudo apt-get -y install musl-tools && rustup target add x86_64-unknown-linux-musl && cargo build --all-features --release --target x86_64-unknown-linux-musl
          && mkdir -p rstun-linux-musl-x86_64
          && mv target/x86_64-unknown-linux-musl/release/rstunc ./rstun-linux-musl-x86_64/
          && mv target/x86_64-unknown-linux-musl/release/rstund ./rstun-linux-musl-x86_64/
          && tar zcf rstun-linux-musl-x86_64.tar.gz ./rstun-linux-musl-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-linux-musl-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-x86_64:
    name: Windows x86_64
    runs-on: windows-latest
    needs: create-tag
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - run:
          cargo build --all-features --release && mkdir -p rstun-windows-x86_64
          && mv target/release/rstunc.exe ./rstun-windows-x86_64/
          && mv target/release/rstund.exe ./rstun-windows-x86_64/
          && 7z a rstun-windows-x86_64.zip ./rstun-windows-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  darwin-x86_64:
    name: Darwin x86_64
    runs-on: macos-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - run:
          rustup target add x86_64-apple-darwin && cargo build --all-features --release --target x86_64-apple-darwin
          && mkdir -p rstun-darwin-x86_64
          && mv target/x86_64-apple-darwin/release/rstunc ./rstun-darwin-x86_64/
          && mv target/x86_64-apple-darwin/release/rstund ./rstun-darwin-x86_64/
          && zip rstun-darwin-x86_64.zip ./rstun-darwin-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-darwin-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  darwin-aarch64:
    name: Darwin Aarch64
    runs-on: macos-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
      - run:
          rustup target add aarch64-apple-darwin && cargo build --all-features --release --target aarch64-apple-darwin
          && mkdir -p rstun-darwin-aarch64
          && mv target/aarch64-apple-darwin/release/rstunc ./rstun-darwin-aarch64/
          && mv target/aarch64-apple-darwin/release/rstund ./rstun-darwin-aarch64/
          && zip rstun-darwin-aarch64.zip ./rstun-darwin-aarch64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-darwin-aarch64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-armv7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - run:
          rustup target add armv7-unknown-linux-gnueabihf && cargo install cross --git https://github.com/cross-rs/cross
          && cross build --all-features --release --target armv7-unknown-linux-gnueabihf
          && mkdir -p rstun-linux-armv7
          && mv target/armv7-unknown-linux-gnueabihf/release/rstunc ./rstun-linux-armv7/
          && mv target/armv7-unknown-linux-gnueabihf/release/rstund ./rstun-linux-armv7/
          && tar zcf rstun-linux-armv7.tar.gz ./rstun-linux-armv7/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-linux-armv7.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-aarch64:
    name: Linux Aarch64
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - run:
          rustup target add aarch64-unknown-linux-gnu && cargo install cross --git https://github.com/cross-rs/cross
          && cross build --all-features --release --target aarch64-unknown-linux-gnu
          && mkdir -p rstun-linux-aarch64
          && mv target/aarch64-unknown-linux-gnu/release/rstunc ./rstun-linux-aarch64/
          && mv target/aarch64-unknown-linux-gnu/release/rstund ./rstun-linux-aarch64/
          && tar zcf rstun-linux-aarch64.tar.gz ./rstun-linux-aarch64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-linux-aarch64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-musl-aarch64:
    name: Linux musl Aarch64
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - run: sudo apt-get -y install musl-tools && rustup target add aarch64-unknown-linux-musl
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: cross build --all-features --release --target aarch64-unknown-linux-musl
      - run: mkdir -p rstun-linux-musl-aarch64
      - run: mv target/aarch64-unknown-linux-musl/release/rstunc ./rstun-linux-musl-aarch64/
      - run: mv target/aarch64-unknown-linux-musl/release/rstund ./rstun-linux-musl-aarch64/
      - run: tar zcf rstun-linux-musl-aarch64.tar.gz ./rstun-linux-musl-aarch64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-linux-musl-aarch64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android-aarch64:
    name: Android ARM64
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - name: Install Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r25c" >> $GITHUB_ENV
      - run: rustup target add aarch64-linux-android
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Add android_logger dependency
        run: |
          if ! grep -q "android_logger" Cargo.toml; then
            echo 'Adding android_logger dependency'
            echo '[target.aarch64-linux-android.dependencies]' >> Cargo.toml
            echo 'android_logger = "0.13"' >> Cargo.toml
          fi
      - run: cross build --all-features --release --target aarch64-linux-android
      - run: mkdir -p rstun-android-aarch64
      - run: mv target/aarch64-linux-android/release/rstunc ./rstun-android-aarch64/
      - run: mv target/aarch64-linux-android/release/rstund ./rstun-android-aarch64/
      - run: zip rstun-android-aarch64.zip ./rstun-android-aarch64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-android-aarch64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android-armv7:
    name: Android ARMv7
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-linux-androideabi
          override: true
      - name: Install Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r25c" >> $GITHUB_ENV
      - run: rustup target add armv7-linux-androideabi
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Add android_logger dependency
        run: |
          if ! grep -q "android_logger" Cargo.toml; then
            echo 'Adding android_logger dependency'
            echo '[target.armv7-linux-androideabi.dependencies]' >> Cargo.toml
            echo 'android_logger = "0.13"' >> Cargo.toml
          fi
      - run: cross build --all-features --release --target armv7-linux-androideabi
      - run: mkdir -p rstun-android-armv7
      - run: mv target/armv7-linux-androideabi/release/rstunc ./rstun-android-armv7/
      - run: mv target/armv7-linux-androideabi/release/rstund ./rstun-android-armv7/
      - run: zip rstun-android-armv7.zip ./rstun-android-armv7/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-android-armv7.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android-x86_64:
    name: Android x86_64
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-linux-android
          override: true
      - name: Install Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r25c" >> $GITHUB_ENV
      - run: rustup target add x86_64-linux-android
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: cross build --all-features --release --target x86_64-linux-android
      - run: mkdir -p rstun-android-x86_64
      - run: mv target/x86_64-linux-android/release/rstunc ./rstun-android-x86_64/
      - run: mv target/x86_64-linux-android/release/rstund ./rstun-android-x86_64/
      - run: zip rstun-android-x86_64.zip ./rstun-android-x86_64/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-tag.outputs.tag_name }}
          files: |
            rstun-android-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
